// <auto-generated />
using System;
using GsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603222803_AdicionandoYoloEClima")]
    partial class AdicionandoYoloEClima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GsApi.Model.PredictionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Acceleration")
                        .HasColumnType("float");

                    b.Property<string>("AlertLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("HeartRate")
                        .HasColumnType("float");

                    b.Property<bool?>("IsAccurate")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PredictedAnomaly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PressureHpa")
                        .HasColumnType("float");

                    b.Property<double>("Probability")
                        .HasColumnType("float");

                    b.Property<string>("SpeciesId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<int>("YoloBirdCount")
                        .HasColumnType("int");

                    b.Property<double>("YoloMovementIndex")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PredictionHistories");
                });

            modelBuilder.Entity("GsApi.Model.SpaceEquipment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("SpaceEquipments");

                    b.HasDiscriminator<string>("EquipmentType").HasValue("SpaceEquipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GsApi.Model.BiotelemetryTag", b =>
                {
                    b.HasBaseType("GsApi.Model.SpaceEquipment");

                    b.Property<string>("SpeciesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("TagBiotelemetria");
                });

            modelBuilder.Entity("GsApi.Model.Satellite", b =>
                {
                    b.HasBaseType("GsApi.Model.SpaceEquipment");

                    b.Property<double>("OrbitAltitude")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("SateliteLEO");
                });
#pragma warning restore 612, 618
        }
    }
}
